(select tool CRC .)
set trace on .
set trace select off .
trace select ---- metaNarrowingSearch
             ---- metaNarrowSearch
             ---- prepNarrowingSols
             ---- crcCritPairs
             delete
             .
set print conceal on .
print conceal fmod_is_sorts_____endfm
              mod_is_sorts______endm
              .
set trace condition off .
set trace whole off .
set trace substitution off .

(ccr SET-ALGEBRA .)
