(select tool CRC .)
set trace off .
set trace select on .
trace select metaNarrowingSearch
             metaNarrowSearch
             ---- prepNarrowingSols
             ---- crcCritPairs
             ---- delete
             .
set print conceal off .
print conceal fmod_is_sorts_____endfm
              mod_is_sorts______endm
              .
set trace condition on .
set trace whole on .
set trace substitution on .

(ccr SET-ALGEBRA .)
