fmod STACK is
  protecting INT .

  sort Int? .
  subsort Int < Int? .
  sorts NeStack Stack Stack? .
  subsort NeStack < Stack < Stack? .

  op empty : -> Stack? [ctor] .
  op push : Int? Stack? -> Stack? [ctor] .
  
  mb empty : Stack .
  mb push(I, S) : NeStack .
  
  op pop : NeStack -> Stack . 
  op top : NeStack -> Int . 

  var S : Stack . 
  var I : Int . 

  eq pop(push(I, S)) = S . 

  eq top(push(I, S)) = I .
endfm