set print conceal off .

fmod NAT2 is
  sort Nat2 .
  op 0 : -> Nat2 [ctor] .
  op s_ : Nat2 -> Nat2 [ctor] .
  op _+_ : Nat2 Nat2 -> Nat2 [comm] .
  vars M N : Nat2 .
  eq M + 0 = M .
  eq M + s N = s(M + N) .
endfm

select FULL-MAUDE .
loop init .

(select EQUALITY-ENRICHMENT .)

(red eq-enrich(upModule('NAT2, true)) .)

eof

(load eq-enrich(upModule('NAT2, true)) .)

red in EQUALITY-ENRICHMENT : eq-enrich(upModule('NAT2, true)) . 