set include BOOL off .


mod READERS-WRITERS is 
    sort Nat .
    op 0 : -> Nat [ctor] .
    op s : Nat -> Nat [ctor] . ---- iter not supported by tools  
     
    sort RWState .
    op <_`,_> : Nat Nat -> RWState [ctor] .  --- readers/writers
    
    vars R W : Nat .
    rl < 0, 0 > => < 0, s(0) > .
    rl < R, s(W) > => < R, W > .
    rl < R, 0 > => < s(R), 0 > .
    rl < s(R), W > => < R, W > .
endm

