---- Maude includes the BOOL file by default, I must deactivate it.
set include BOOL off .
---- Since the module in the file does not use parentheses, it must be loaded before the MFE
---- I could load the MFE first, but then I need to re-start the loop
load maa0.maude
load ../../src/mfe.maude

---- Church-Rosser check
(select tool CRC .)
(ccr MAA .)

---- Termination check
(select tool MTT .)
(select external tool aprove .)
(ct MAA .)
